### PR TITLE
[docs] Added code highlighting

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by RyanThompson** [comment]
Dang! Code highlighting only works with the ``` and not indenting!?

**Comment by Piterden** [comment]
It shouldn't be indented.

**Comment by RyanThompson** [comment]
Indenting in markdown is for code too though? Or am I mistaken..

**Comment by Piterden** [comment]
https://guides.github.com/features/mastering-markdown/
Ya. Code tab ^

**Pull request merged**
